def build(bld):
    bld.recurse('pkg')
    main = bld.new_task_gen(
        features = 'go goprogram',
        target   = 'bin/main',
        use = ['a', 'b'],
        source   = 'main.go',
        chmod = 0755,
        name = 'main'
    )