#!/usr/bin/env python
# By: Tom Wambold <tom5760@gmail.com>
# wscript - Waf build script

import Logs
Logs.colors_lst['USE'] = False

top = 'src'
out = 'build'

def options(opt):
    pass

def configure(conf):
    conf.load('go')
    conf.load('waf_unit_test')

def build(bld):
    bld.add_subdirs('src')